name: Build Frontend

on:
  push:
    branches: ["main", "testing"]
  pull_request:
    branches: ["main", "testing"]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/tournament_manager_frontend
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=testing,enable=${{ github.ref == 'refs/heads/testing' }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_PUBLIC_API_URL=${{ secrets.VITE_PUBLIC_API_URL }}
            VITE_PUBLIC_ENABLE_LIVE_SCORES=${{ vars.VITE_PUBLIC_ENABLE_LIVE_SCORES || 'true' }}
